core: Die with a helpful message when an exception is raised in state update
Summary:
Marksman core doesn't use exceptions for regular control flow so any
exception originating in the core is basically an assert violation.

Outside of server bugs one potential source of exceptions in core is
bugs in clients (e.g. incremental text sync).

Previously, such exception would cause a thread die a silent death in
the guts of async, followed by the process dying because of the timeout
on async response.

This is not helpful because the original exception gets lost, so good
luck debugging what was wrong.

Now the process will just die right away but it'll output a helpful
message together with the original exception, which makes debugging so
much easier.

Example of a message:
```
---------------------------------------------------------------------------
Marksman encountered a fatal error
Please, report the error at https://github.com/artempyanykh/marksman/issues
---------------------------------------------------------------------------
Marksman version: 1.0.0.0
OS: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
Arch: Arm64
Client: emacsGNU Emacs 28.2 (build 1, aarch64-apple-darwin22.2.0, Carbon Version 169 AppKit 2299.3)
 of 2023-02-12
Workspace:
  Revision      : 1
  Folder count  : 1
  Document count: 1
  User config   : absent
---------------------------------------------------------------------------
System.Exception: Position outside of line map: (4,11)
   at Marksman.Text.FindOffset@58.Invoke(Unit _arg2) in /Users/arr/dev/marksman/Marksman/Text.fs:line 58
   at Marksman.Text.LineMap.FindOffset(Position pos) in /Users/arr/dev/marksman/Marksman/Text.fs:line 58
   at Marksman.Text.applyChangeOne(Text text, TextDocumentContentChangeEvent change) in /Users/arr/dev/marksman/Marksman/Text.fs:line 188
   at Marksman.Text.applyTextChange@202.Invoke(Text text, TextDocumentContentChangeEvent change)
   at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder, TState state, T[] array) in D:\a\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 901
   at Marksman.Text.applyTextChange(TextDocumentContentChangeEvent[] changeEvents, Text text) in /Users/arr/dev/marksman/Marksman/Text.fs:line 202
   at Marksman.Workspace.DocModule.applyLspChange(DidChangeTextDocumentParams change, Doc doc) in /Users/arr/dev/marksman/Marksman/Workspace.fs:line 87
   at Marksman.Server.TextDocumentDidChange@569.Invoke(State state) in /Users/arr/dev/marksman/Marksman/Server.fs:line 575
   at Marksman.Server.mutator@423.Invoke(State state) in /Users/arr/dev/marksman/Marksman/Server.fs:line 423
   at Marksman.Server.go@366-6.Invoke(StateMessage _arg1) in /Users/arr/dev/marksman/Marksman/Server.fs:line 377

Process marksman stderr finished
```